---
# tasks file for ansible-role-edgeos
- name: collect all facts from the device
  edgeos_facts:
    gather_subset: all
  register: l_edge_os_facts

- name: configure the remote device
  edgeos_config:
    lines: "{{ edgeos_config_lines }}"
